- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"

    fonts_dir: "{{ lookup('env', 'HOME') }}/Library/Fonts"
  pre_tasks:
    - name: Ensure that Homebrew is installed
      shell: command -v brew
      register: homebrew_exists
      changed_when: false
      ignore_errors: true
      tags:
        - install
        - core

    - name: Install Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when: not homebrew_exists
      tags:
        - install
        - core

    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/homebrew-setup.yml
    - import_tasks: tasks/fonts-setup.yml
    - import_tasks: tasks/rust-setup.yml
