- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "d4vsanchez@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "David Sánchez"
  tags:
  - git-personal

